### ISSUE TITLE
error when trying to generate report

### ISSUE THREAD

**Issue by markshannon1974** [vesposito/easyucs#12]
hi

i am trying to generate a report and get the below:-

Traceback (most recent call last):
  File "easyucs.py", line 775, in <module>
    main()
  File "easyucs.py", line 768, in main
    init_process(ucs_device, args, json_string)
  File "easyucs.py", line 331, in init_process
    ucs_device.inventory_manager.draw_inventory()
  File "C:\Users\Documents\GitHub\easyucs\inventory\ucs\manager.py", line 166, in draw_inventory
    infra = UcsSystemDrawInfraChassis(chassis=chassis_draw,
  File "C:\Users\Documents\GitHub\easyucs\draw\ucs\chassis.py", line 644, in __init__
    self.background = self._create_background(self.canvas_width, self.canvas_height, self.canvas_color)
  File "C:\Users\Documents\GitHub\easyucs\draw\object.py", line 154, in _create_background
    return Image.new('RGBA', (width, height), color)
  File "C:\Users\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 2578, in new
    return im._new(core.fill(mode, size, color))
MemoryError

thanks

**Comment by vesposito** [comment]
Hello Mark,
It looks like you are using Python in 32-bit mode. Can you please try using Python in 64-bit mode instead?

Currently, the pictures generation process can take quite a large amount of memory, because it is generating all pictures in RAM, and then writes them to disk. On heavy environments with lots of servers, this can consume up to 8GB of RAM temporarily.

Python in 32-bit mode can only address up to 4GB of RAM, which probably explains the error message you're getting.

**Comment by markshannon1974** [comment]
This worked perfectly when used 64bit.

Thanks.

**Comment by vesposito** [comment]
Glad to see it works fine. Thanks for the feedback!
