### ISSUE TITLE
Error gathering memory error stats on UCSPE

### ISSUE THREAD

**Issue by lengoldenstein** [vesposito/easyucs#17]
Trying to gather a report from a UCSPE (Platform Emulator) instance.  It appears to be failing at gathering memory DIMM error stats.  
This works correctly on a proper physical UCS-M instance.  

I saw:
- Add inventory of memory errors per DIMM in UCSM inventory

is a new feature in 9.7.4.  Bug perhaps?

goldel@L011124:~/git/easyucs$ python3 easyucs.py report generate -t ucsm -i 10.33.114.108 -u XXX -p YYY -o reports

EasyUCS 0.9.7.4 created by Marc Abu El Ghait, Franck Bonneau and Vincent Esposito, Copyright 2016-2021, Cisco

2021-03-10 12:52:20,082 :: INFO :: 10.33.114.108 :: device.py :: in connect :: Trying to connect to UCS System: 10.33.114.108
2021-03-10 12:52:20,520 :: INFO :: 10.33.114.108 :: device.py :: in connect :: Connected to UCSPE-10-33-114-108 running version 4.1(2c)
2021-03-10 12:52:20,521 :: WARNING :: 10.33.114.108 :: device.py :: in connect :: Version 4.1(2c) running is not yet supported by ucsmsdk!
2021-03-10 12:52:20,543 :: INFO :: 10.33.114.108 :: manager.py :: in fetch_config :: Fetching config from live device (can take several minutes)
2021-03-10 12:53:17,287 :: WARNING :: 10.33.114.108 :: admin.py :: in __init__ :: Password of SEL Policy  can't be exported
2021-03-10 12:53:17,288 :: WARNING :: 10.33.114.108 :: admin.py :: in __init__ :: Password of Local User admin can't be exported
2021-03-10 12:53:17,594 :: INFO :: 10.33.114.108 :: manager.py :: in fetch_config :: Finished fetching config with UUID 2d2c6bf0-7b32-4dc7-9d3c-3954e45e2306 from live device
2021-03-10 12:53:17,612 :: INFO :: 10.33.114.108 :: manager.py :: in fetch_inventory :: Fetching inventory from live device (can take several minutes)
2021-03-10 12:53:34,750 :: WARNING :: 10.33.114.108 :: manager.py :: in fetch_inventory :: Info Policy is disabled. No neighbors can be found
2021-03-10 12:53:34,833 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 1 for server 1 are not available.
2021-03-10 12:53:34,836 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 2 for server 1 are not available.
2021-03-10 12:53:34,840 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 3 for server 1 are not available.
2021-03-10 12:53:34,844 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 4 for server 1 are not available.
2021-03-10 12:53:34,911 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 1 for server 1 are not available.
2021-03-10 12:53:34,915 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 2 for server 1 are not available.
2021-03-10 12:53:34,919 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 3 for server 1 are not available.
2021-03-10 12:53:34,923 :: INFO :: 10.33.114.108 :: memory.py :: in _find_corresponding_memory_error_stats :: Error stats of memory with id 4 for server 1 are not available.
Traceback (most recent call last):
  File "easyucs.py", line 813, in <module>
    main()
  File "easyucs.py", line 806, in main
    init_process(ucs_device, args, json_string)
  File "easyucs.py", line 319, in init_process
    ucs_device.inventory_manager.fetch_inventory()
  File "/home/goldel/git/easyucs/inventory/ucs/manager.py", line 348, in fetch_inventory
    inventory.chassis.append(UcsSystemChassis(parent=inventory, equipment_chassis=equipment_chassis))
  File "/home/goldel/git/easyucs/inventory/ucs/chassis.py", line 172, in __init__
    self.blades = self._get_blades()
  File "/home/goldel/git/easyucs/inventory/ucs/chassis.py", line 274, in _get_blades
    return self._inventory.get_inventory_objects_under_dn(dn=self.dn, object_class=UcsSystemBlade, parent=self)
  File "/home/goldel/git/easyucs/inventory/ucs/inventory.py", line 142, in get_inventory_objects_under_dn
    easyucs_objects_list.append(object_class(parent, sdk_object))
  File "/home/goldel/git/easyucs/inventory/ucs/blade.py", line 128, in __init__
    UcsBlade.__init__(self, parent=parent, compute_blade=compute_blade)
  File "/home/goldel/git/easyucs/inventory/ucs/blade.py", line 36, in __init__
    self.memory_arrays = self._get_memory_arrays()
  File "/home/goldel/git/easyucs/inventory/ucs/blade.py", line 239, in _get_memory_arrays
    parent=self)
  File "/home/goldel/git/easyucs/inventory/ucs/inventory.py", line 142, in get_inventory_objects_under_dn
    easyucs_objects_list.append(object_class(parent, sdk_object))
  File "/home/goldel/git/easyucs/inventory/ucs/memory.py", line 31, in __init__
    UcsMemoryArray.__init__(self, parent=parent, memory_array=memory_array)
  File "/home/goldel/git/easyucs/inventory/ucs/memory.py", line 23, in __init__
    self.memory_units = self._get_memory_units()
  File "/home/goldel/git/easyucs/inventory/ucs/memory.py", line 42, in _get_memory_units
    parent=self)
  File "/home/goldel/git/easyucs/inventory/ucs/inventory.py", line 142, in get_inventory_objects_under_dn
    easyucs_objects_list.append(object_class(parent, sdk_object))
  File "/home/goldel/git/easyucs/inventory/ucs/memory.py", line 146, in __init__
    error_stats = self._find_corresponding_memory_error_stats()
  File "/home/goldel/git/easyucs/inventory/ucs/memory.py", line 174, in _find_corresponding_memory_error_stats
    self.dn + " of model \"" + self.model + "\" with ID " + self.id)
TypeError: must be str, not NoneType

**Comment by vesposito** [comment]
Hello,
Thanks for your issue report.
I'm guessing the issue appears because UCS PE sometimes do not set all attributes of each object, meaning the "model" field is probably empty, which causes the error in a logging message statement.

I've just pushed a new commit that I hope will fix the issue. Let me know how it goes:
https://github.com/vesposito/easyucs/commit/4aad9c41285effd48c1b36ed958a51e9d4b05b8a

Thanks,
  Vincent

**Comment by lengoldenstein** [comment]
Works great!  Ran cleanly and generated the report from UCE PE.  Thank you!

**Comment by vesposito** [comment]
You're welcome!
Closing this issue then.
