### ISSUE TITLE
'TLSConnection' object has no attribute 'key_file' whenever I try to connect to a UCS Manager or UCS Central

### ISSUE THREAD

**Issue by ColWhackaMole** [vesposito/easyucs#28]
Hello,

Whenever I try to connect to a UCS Manager or UCS Central to do a fetch config, inventory, etc. I get the following error:

Task: Fetch config from UCS System
Failed

Error while trying to connect to UCS System: 10.143.250.70: 'TLSConnection' object has no attribute 'key_file'

EasyUCS Version: 0.9.8.7

Debug Logs:
`2024-04-03 11:50:57,327 :: debug :: 10.141.0.70 :: device.py :: in connect :: Using UCS Central SDK version 0.9.0.4
2024-04-03 11:50:57,328 :: info :: 10.141.0.70 :: device.py :: in connect :: Trying to connect to UCS Central: 10.141.0.70
2024-04-03 11:50:57,429 :: error :: 10.141.0.70 :: device.py :: in connect :: Error while trying to connect to UCS Central: 10.141.0.70: 'TLSConnection' object has no attribute 'key_file'
2024-04-03 12:15:04,522 :: debug :: 10.143.250.70 :: device.py :: in connect :: Using UCS System SDK version 0.9.16
2024-04-03 12:15:04,522 :: info :: 10.143.250.70 :: device.py :: in connect :: Trying to connect to UCS System: 10.143.250.70
2024-04-03 12:15:04,710 :: error :: 10.143.250.70 :: device.py :: in connect :: Error while trying to connect to UCS System: 10.143.250.70: 'TLSConnection' object has no attribute 'key_file'`

Can you please assist? I have been unable to find any solutions via Google/Forums.

Thank you in advanced for your time and assistance.

**Comment by ColWhackaMole** [comment]
could this be due to self-signed certs on the ucs manager & ucs central?

**Comment by vesposito** [comment]
Hello, it is unlikely due to self-signed certs as ucsmsdk and ucscsdk are ignoring the SSL validation by default. However this error message does seem to be coming from the SDKs themselves, and not EasyUCS.

Which version of Python are you using?

Could you please try to run a small Python script to check if you are able to connect to your UCS Manager? Something like described here: https://ucsmsdk.readthedocs.io/en/latest/ucsmsdk_ug.html#connecting-disconnecting

**Comment by ColWhackaMole** [comment]
I am using v3.12.2150.0 of Python. Is there another version I should be using?

I will try putting together a small python script and see if I can reach a UCS Manager. I'll let you know the results of my test once complete.

Thanks again for your time and assistance.

**Comment by ColWhackaMole** [comment]
I got the same error via the script described in the link provided. Please see the output below for your reference.

--------

PS C:\Users\~\easyucs-master> python.exe .\test.py
Traceback (most recent call last):
  File "C:\Users\~\easyucs-master\test.py", line 7, in <module>
    handle.login()
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucshandle.py", line 135, in login
    return self._login(auto_refresh, force, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucssession.py", line 599, in _login
    response = self.post_elem(elem, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucssession.py", line 315, in post_elem
    response_str = self.post_xml(xml_str, timeout=timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucssession.py", line 264, in post_xml
    response_str = self.post(uri=ucsm_uri, data=xml_str, read=read, timeout=timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucssession.py", line 243, in post
    response = self.__driver.post(uri=uri, data=data, read=read,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucsdriver.py", line 262, in post
    response = opener.open(request, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucsdriver.py", line 55, in https_open
    return self.do_open(TLSConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1085, in _send_output
    self.send(msg)
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1029, in send
    self.connect()
  File "C:\Users\~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ucsmsdk\ucsdriver.py", line 87, in connect
    if self.key_file and self.cert_file:
       ^^^^^^^^^^^^^
AttributeError: 'TLSConnection' object has no attribute 'key_file'

--------

**Comment by vesposito** [comment]
Can you try using an older Python version (3.11 or older)? This is a bug in ucsmsdk, as you can see here: https://github.com/CiscoUcs/ucsmsdk/issues/240

**Comment by ColWhackaMole** [comment]
That fixed it! Running Python v3.11.9150.0 fixed the issue. Thanks so much for your time and assistance resolving this :)

**Comment by vesposito** [comment]
Great news! Thanks for the feedback. Hopefully the ucsmsdk team can fix this issue with Python 3.12 soon.
