### ISSUE TITLE
C++ Not recognized when using requrements.txt under msvc.py 

### ISSUE THREAD

**Issue by michern1102** [vesposito/easyucs#29]
I keep getting the following error out of the build wheel for the script.

`Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "<string>", line 105, in uses_msvc
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\msvc.py", line 230, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MikeErnst\AppData\Local\Temp\pip-build-env-gzwa1pa5\overlay\Lib\site-packages\setuptools\msvc.py", line 187, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

Notes:
Windows 11
Using VSCode in administrator mode
Git installed
Python installed
C++ 14.0 installed via Build Tools

Should I modify something to allow this to continue?

Thanks!

**Comment by vesposito** [comment]
Looks like an issue with Python/Pip itself...
Could you try with a lower version of Python, like 3.10 or 3.11? I believe Python 3.12 causes issues with the UCS Manager/Central SDKs that EasyUCS is using. Not sure this is related, but it would likely be necessary to make it work anyway...

**Comment by michern1102** [comment]
tried 3.11 same error

https://app.screencast.com/M1zxUgeuSoSbc?tab=Details&conversation=I2yLyVFSB5SJ2B1FeM1cys

I could go 3.10 if you think it would be worth a try.

**Comment by vesposito** [comment]
Not sure about 3.10... can you take a look at this?
https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst
I suspect one of the required modules from EasyUCS itself requires Microsoft Visual C++ runtime.

**Comment by vesposito** [comment]
Any update on this?

**Comment by michern1102** [comment]
Hey Vincent, after installing the C++ build tools it looks to be working. I will try to run the script sometime today and see what we get. Thank you for your efforts on this!

**Comment by michern1102** [comment]
Side question... It looks like EasyUCS only does reporting from a UCSM standpoint. I do not see the arg "intersight" under the report portion only the deploy portion. Are there plans to have a report generator for intersight in the future as well or is it here and I am missing something?

Thanks!

**Comment by vesposito** [comment]
The reason the reporting does not work with Intersight is that we are missing the inventory part for an Intersight device. The inventory part is crucial to be able to construct the report, and so it is our next big task in EasyUCS. This is definitely planned, however it takes some time to build...
Once we have the inventory, we should be able to build a report similarly to what we have built for UCSM.
Hope this makes sense!
